# Generated by Django 4.0 on 2022-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationForTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_currency', models.CharField(choices=[('EUR', 'EUR'), ('CHF', 'CHF'), ('USD', 'USD')], default='EUR', max_length=3)),
            ],
        ),
    ]
