# Generated by Django 4.0 on 2022-01-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationfortransaction',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='transactions.wallet', verbose_name='Information'),
        ),
    ]
